services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass1!!
      MYSQL_DATABASE: studyboard
      MYSQL_USER: user1
      MYSQL_PASSWORD: rootpass1!!
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  board-app:
    build: ../..
    image: board-app
    container_name: board-container
    expose:
      - "8081"
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/studyboard?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: user1
      SPRING_DATASOURCE_PASSWORD: rootpass1!!
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - board-app
    networks:
      - backend

volumes:
  mysql-data:

networks:
  backend:

on:
jobs:
